### ISSUE TITLE
bird-to-pipe collision detection misses collisions

### ISSUE THREAD

**Issue by InDieTasten** [ellisonleao/clumsy-bird#61] opened 2015-03-10 22:34 UTC
Whilst playing I noticed that the upper part of the bird is actually not colliding with the top pipes(On certain frames the bird is drawn beneath it, or on top of it), which makes it look like the "collision mesh" of the bird consists of a single horizontal line or even point. (Although it's totally possible for the pipe to not having an accurate collision mesh)

It's a rather minor improvement you could easily fix by drawing either the top pipe segments a little higher than the current collision mesh, but I'm not sure how your collision is working. Otherwise I would be pushing a pull request :wink: .

**Comment by ellisonleao** [comment] 2015-03-10 22:55
i am using a bounding box with the size of the pipe:
https://github.com/ellisonleao/clumsy-bird/blob/gh-pages/js/entities/entities.js#L117

For the bird i am using a custom bounding box too:
https://github.com/ellisonleao/clumsy-bird/blob/gh-pages/js/entities/entities.js#L21

the collision is being handled on the BirdEntity `onCollision` function here:
https://github.com/ellisonleao/clumsy-bird/blob/gh-pages/js/entities/entities.js#L70-L83

the `hit` entity is just a non drawable entity to check if the user just passed by a pipe. If you have any improvements, please let me know!

I can re-add the debug panel if you want, which lets you check the bounding boxes in realtime.

**Comment by ellisonleao** [comment] 2015-04-14 18:04
any updates @InDieTasten  ?

**Comment by InDieTasten** [comment] 2015-04-15 04:33
Nope, sorry, I haven't got time to get into the code and fix it.
It's also a quite minor issue

**Comment by shimmy568** [comment] 2015-04-16 20:21
From looking at the code I think this is from the fact that when you rotate the image you don't rotate the bounding box to fit it so when it faces down or up the bounding box fits it. What i would recommend to fix the bug is using the Polygon in the melonJS instead of the Rect or just using a simple toPolygon call on the object you have at the moment. You can use the rotate method in the polygon class to match it with the image. I'm going to try to fix it but i haven't touched javascript in many years and it may take a while to get back in the groove.

**Comment by ellisonleao** [comment] 2015-04-23 21:55
you're right @shimmy568 . The problem is melonJS doesn't rotate the bounding box when i rotate the sprite object, so at i've changed the bird's bouding box to a ellipse, improving a little more the collision. I've also re-enabled the debug mode on the game, so you guys can test. Just go to http://ellisonleao.github.io/clumsy-bird/#debug and enable the `hitbox` option. I am closing this one for now. If anyone has any problems please comment and i will reopen it.

**Closed by ellisonleao** 2015-04-23 21:55 UTC
